name: firebase_storage_web
description: The web implementation of firebase_storage
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
version: 1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart

dependencies:
  firebase: ^7.0.0
  firebase_storage_platform_interface:
    path: ../firebase_storage_platform_interface

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.2+1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"