name: firebase_storage
description: Flutter plugin for Firebase Cloud Storage, a powerful, simple, and
  cost-effective object storage service for Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage
version: 3.1.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.storage
        pluginClass: FirebaseStoragePlugin
      ios:
        pluginClass: FLTFirebaseStoragePlugin
      web:
        default_package: firebase_storage_web

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  firebase_storage_platform_interface:
    path: ../firebase_storage_platform_interface
  firebase_storage_web:
    path: ../firebase_storage_web

dev_dependencies:
  http: ^0.12.0
  flutter_test:
    sdk: flutter
  uuid: "^1.0.0"
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
